version: "2"
services:
  apostrophe:
    container_name: apostrophe
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - ./data/uploads:/app/public/uploads
      - ./lib:/app/lib
    environment:
      - APOS_MONGODB_URI=mongodb://mongo:27017/db
    depends_on:
      - mongo
#    command: nodemon --watch lib -e js,html server.js
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - "27017"
